//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class boletaItem
    {
        public int idProyectoItem { get; set; }
        public int idBoleta { get; set; }
        public int cantidad { get; set; }
        public int costoActual { get; set; }
    
        public virtual boleta boleta { get; set; }
        public virtual proyectoItem proyectoItem { get; set; }
    }
}
