//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class boletaItem
    {
        public int idItemReajuste { get; set; }
        public int idBoleta { get; set; }
        public decimal cantidad { get; set; }
        public decimal costoTotal { get; set; }
        public decimal redimientos { get; set; }
    
        public virtual boleta boleta { get; set; }
        public virtual itemReajuste itemReajuste { get; set; }
    }
}
