//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingeniero
    {
        public ingeniero()
        {
            this.ingenieroContrato = new HashSet<ingenieroContrato>();
        }
    
        public int idPersona { get; set; }
        public string descripcion { get; set; }
        public string departamento { get; set; }
        public string rol { get; set; }
    
        public virtual ICollection<ingenieroContrato> ingenieroContrato { get; set; }
        public virtual persona persona { get; set; }
    }
}
