//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemReajuste
    {
        public itemReajuste()
        {
            this.boletaItem = new HashSet<boletaItem>();
            this.proyectoItemReajuste = new HashSet<proyectoItemReajuste>();
        }
    
        public int id { get; set; }
        public int idContratoItem { get; set; }
        public int ano { get; set; }
        public byte mes { get; set; }
        public decimal reajuste { get; set; }
        public decimal precioReajustado { get; set; }
    
        public virtual ICollection<boletaItem> boletaItem { get; set; }
        public virtual contratoItem contratoItem { get; set; }
        public virtual ICollection<proyectoItemReajuste> proyectoItemReajuste { get; set; }
    }
}
