//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.boletaItem = new HashSet<boletaItem>();
            this.subProyectoItem = new HashSet<subProyectoItem>();
        }
    
        public int id { get; set; }
        public string codigoItem { get; set; }
        public string descripcion { get; set; }
        public string unidadMedida { get; set; }
        public int precioUnitario { get; set; }
    
        public virtual ICollection<boletaItem> boletaItem { get; set; }
        public virtual ICollection<subProyectoItem> subProyectoItem { get; set; }
    }
}
