//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Proyecto_IAAEntities : DbContext
    {
        public Proyecto_IAAEntities()
            : base("name=Proyecto_IAAEntities")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<boleta> boleta { get; set; }
        public virtual DbSet<boletaItem> boletaItem { get; set; }
        public virtual DbSet<contratista> contratista { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<contratoItem> contratoItem { get; set; }
        public virtual DbSet<fondo> fondo { get; set; }
        public virtual DbSet<ingeniero> ingeniero { get; set; }
        public virtual DbSet<ingenieroContrato> ingenieroContrato { get; set; }
        public virtual DbSet<inspector> inspector { get; set; }
        public virtual DbSet<item> item { get; set; }
        public virtual DbSet<itemReajuste> itemReajuste { get; set; }
        public virtual DbSet<laboratorioCalidad> laboratorioCalidad { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<pICI> pICI { get; set; }
        public virtual DbSet<planInversion> planInversion { get; set; }
        public virtual DbSet<programa> programa { get; set; }
        public virtual DbSet<programaSubProyectoContratoItem> programaSubProyectoContratoItem { get; set; }
        public virtual DbSet<proyecto_estructura> proyecto_estructura { get; set; }
        public virtual DbSet<ruta> ruta { get; set; }
        public virtual DbSet<seccionControl> seccionControl { get; set; }
        public virtual DbSet<subProyecto> subProyecto { get; set; }
        public virtual DbSet<subproyectoContratoItem> subproyectoContratoItem { get; set; }
        public virtual DbSet<telefono> telefono { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<zona> zona { get; set; }
        public virtual DbSet<oMCI> oMCI { get; set; }
        public virtual DbSet<ordenModificacion> ordenModificacion { get; set; }
    }
}
