//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Proyecto_IAAEntities : DbContext
    {
        public Proyecto_IAAEntities()
            : base("name=Proyecto_IAAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<boleta> boleta { get; set; }
        public virtual DbSet<boletaItem> boletaItem { get; set; }
        public virtual DbSet<contratista> contratista { get; set; }
        public virtual DbSet<contratistaProyecto> contratistaProyecto { get; set; }
        public virtual DbSet<fondo> fondo { get; set; }
        public virtual DbSet<ingeniero> ingeniero { get; set; }
        public virtual DbSet<ingenieroProyecto> ingenieroProyecto { get; set; }
        public virtual DbSet<inspector> inspector { get; set; }
        public virtual DbSet<item> item { get; set; }
        public virtual DbSet<laboratorioCalidad> laboratorioCalidad { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<programa> programa { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<ruta> ruta { get; set; }
        public virtual DbSet<subProyecto> subProyecto { get; set; }
        public virtual DbSet<subProyectoItem> subProyectoItem { get; set; }
        public virtual DbSet<telefono> telefono { get; set; }
        public virtual DbSet<TipoSubproyecto> TipoSubproyecto { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<zona> zona { get; set; }
    }
}
