//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class programa
    {
        public programa()
        {
            this.subProyecto = new HashSet<subProyecto>();
        }
    
        public int id { get; set; }
        public int idProyecto { get; set; }
        public short ano { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFinal { get; set; }
        public byte trimestre { get; set; }
        public int monto { get; set; }
    
        public virtual ICollection<subProyecto> subProyecto { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
