//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class programaSubProyectoContratoItem
    {
        public int id { get; set; }
        public int idPrograma { get; set; }
        public int idSubProyectoContratoItem { get; set; }
    
        public virtual programa programa { get; set; }
        public virtual subproyectoContratoItem subproyectoContratoItem { get; set; }
    }
}
