//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyecto
    {
        public proyecto()
        {
            this.proyectoItem = new HashSet<proyectoItem>();
        }
    
        public int id { get; set; }
        public int idProgProy { get; set; }
        public int idTipoProyecto { get; set; }
        public int idRuta { get; set; }
        public string nombre { get; set; }
    
        public virtual progProy progProy { get; set; }
        public virtual ICollection<proyectoItem> proyectoItem { get; set; }
        public virtual ruta ruta { get; set; }
        public virtual tipoProyecto tipoProyecto { get; set; }
    }
}
