//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class subProyectoItem
    {
        public int id { get; set; }
        public int idSubProyecto { get; set; }
        public int idItem { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFinal { get; set; }
        public int costoEstimado { get; set; }
    
        public virtual item item { get; set; }
        public virtual subProyecto subProyecto { get; set; }
    }
}
