//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class subproyectoContratoItem
    {
        public subproyectoContratoItem()
        {
            this.programaSubProyectoContratoItem = new HashSet<programaSubProyectoContratoItem>();
        }
    
        public int id { get; set; }
        public int idSubProyecto { get; set; }
        public int idContratoItem { get; set; }
    
        public virtual contratoItem contratoItem { get; set; }
        public virtual ICollection<programaSubProyectoContratoItem> programaSubProyectoContratoItem { get; set; }
        public virtual subProyecto subProyecto { get; set; }
    }
}
