//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class zona
    {
        public zona()
        {
            this.Contrato = new HashSet<Contrato>();
            this.ruta = new HashSet<ruta>();
        }
    
        public short id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Contrato> Contrato { get; set; }
        public virtual ICollection<ruta> ruta { get; set; }
    }
}
