//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_IAA_Utilerias {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UtilRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SOP_IAA_Utilerias.UtilRecursos", typeof(UtilRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar el contratista: .
        /// </summary>
        internal static string ERROR_CONTRATISTA_ACTUALIZAR {
            get {
                return ResourceManager.GetString("ERROR_CONTRATISTA_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar el contratista: .
        /// </summary>
        internal static string ERROR_CONTRATISTA_AGREGAR {
            get {
                return ResourceManager.GetString("ERROR_CONTRATISTA_AGREGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el contratista: .
        /// </summary>
        internal static string ERROR_CONTRATISTA_ELIMINAR {
            get {
                return ResourceManager.GetString("ERROR_CONTRATISTA_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar el contrato: .
        /// </summary>
        internal static string ERROR_CONTRATO_ACTUALIZAR {
            get {
                return ResourceManager.GetString("ERROR_CONTRATO_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar el contrato: .
        /// </summary>
        internal static string ERROR_CONTRATO_AGREGAR {
            get {
                return ResourceManager.GetString("ERROR_CONTRATO_AGREGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el contrato: .
        /// </summary>
        internal static string ERROR_CONTRATO_ELIMINAR {
            get {
                return ResourceManager.GetString("ERROR_CONTRATO_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar el Fondo: .
        /// </summary>
        internal static string ERROR_FONDO_ACTUALIZAR {
            get {
                return ResourceManager.GetString("ERROR_FONDO_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar el Fondo: .
        /// </summary>
        internal static string ERROR_FONDO_AGREGAR {
            get {
                return ResourceManager.GetString("ERROR_FONDO_AGREGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el Fondo: .
        /// </summary>
        internal static string ERROR_FONDO_ELIMINAR {
            get {
                return ResourceManager.GetString("ERROR_FONDO_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar el ingeniero: .
        /// </summary>
        internal static string ERROR_INGENIERO_ACTUALIZAR {
            get {
                return ResourceManager.GetString("ERROR_INGENIERO_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar el ingeniero: .
        /// </summary>
        internal static string ERROR_INGENIERO_AGREGAR {
            get {
                return ResourceManager.GetString("ERROR_INGENIERO_AGREGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el ingeniero: .
        /// </summary>
        internal static string ERROR_INGENIERO_ELIMINAR {
            get {
                return ResourceManager.GetString("ERROR_INGENIERO_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar el laboratorio: .
        /// </summary>
        internal static string ERROR_LABORATORIO_ACTUALIZAR {
            get {
                return ResourceManager.GetString("ERROR_LABORATORIO_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar el laboratorio: .
        /// </summary>
        internal static string ERROR_LABORATORIO_AGREGAR {
            get {
                return ResourceManager.GetString("ERROR_LABORATORIO_AGREGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al elimnar el laboratorio: .
        /// </summary>
        internal static string ERROR_LABORATORIO_ELIMINAR {
            get {
                return ResourceManager.GetString("ERROR_LABORATORIO_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar la persona: .
        /// </summary>
        internal static string ERROR_PERSONA_ACTUALIZAR {
            get {
                return ResourceManager.GetString("ERROR_PERSONA_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar la persona: .
        /// </summary>
        internal static string ERROR_PERSONA_AGREGAR {
            get {
                return ResourceManager.GetString("ERROR_PERSONA_AGREGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al elimnar la persona: .
        /// </summary>
        internal static string ERROR_PERSONA_ELIMINAR {
            get {
                return ResourceManager.GetString("ERROR_PERSONA_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar el proyecto: .
        /// </summary>
        internal static string ERROR_PROYECTO_ACTUALIZAR {
            get {
                return ResourceManager.GetString("ERROR_PROYECTO_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar el proyecto: .
        /// </summary>
        internal static string ERROR_PROYECTO_AGREGAR {
            get {
                return ResourceManager.GetString("ERROR_PROYECTO_AGREGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el proyecto: .
        /// </summary>
        internal static string ERROR_PROYECTO_ELIMINAR {
            get {
                return ResourceManager.GetString("ERROR_PROYECTO_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar la ruta: .
        /// </summary>
        internal static string ERROR_RUTA_ACTUALIZAR {
            get {
                return ResourceManager.GetString("ERROR_RUTA_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar la ruta: .
        /// </summary>
        internal static string ERROR_RUTA_AGREGAR {
            get {
                return ResourceManager.GetString("ERROR_RUTA_AGREGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar la ruta: .
        /// </summary>
        internal static string ERROR_RUTA_ELIMINAR {
            get {
                return ResourceManager.GetString("ERROR_RUTA_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar el proyecto: .
        /// </summary>
        internal static string ERROR_ZONA_ACTUALIZAR {
            get {
                return ResourceManager.GetString("ERROR_ZONA_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar el proyecto: .
        /// </summary>
        internal static string ERROR_ZONA_AGREGAR {
            get {
                return ResourceManager.GetString("ERROR_ZONA_AGREGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el proyecto: .
        /// </summary>
        internal static string ERROR_ZONA_ELIMINAR {
            get {
                return ResourceManager.GetString("ERROR_ZONA_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar esta boleta?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_BOLETA {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_BOLETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar este contratista?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_CONTRATISTA {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_CONTRATISTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar este contrato?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_CONTRATO {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_CONTRATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar este fondo?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_FONDO {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_FONDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar este ingeniero?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_INGENIERO {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_INGENIERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar este inspector?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_INSPECTOR {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_INSPECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar este item?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_ITEM {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar este item del contrato?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_ITEM_CONTRATO {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_ITEM_CONTRATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar este item del proyecto?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_ITEM_PROYECTO {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_ITEM_PROYECTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar este laboratorio?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_LABORATORIO {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_LABORATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar el plan de este mes?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_PLAN {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar este programa?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_PROGRAMA {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_PROGRAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar este proyecto?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_PROYECTO {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_PROYECTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar este proyecto/estructura?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_PROYECTO_ESTRUCTURA {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_PROYECTO_ESTRUCTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar los reajustes de este mes?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_REAJUSTES {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_REAJUSTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar la sección de control?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_SC {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar esta zona?.
        /// </summary>
        internal static string MSJ_CONFIRM_ELIMINAR_ZONA {
            get {
                return ResourceManager.GetString("MSJ_CONFIRM_ELIMINAR_ZONA", resourceCulture);
            }
        }
    }
}
